---
title: "TINMAN 16S Format Metadata"
author: "Rachel Rodgers"
date: "`r Sys.Date()`"
output: html_document
---

```{r load-libraries, message=FALSE}
library("readxl")
library("janitor")
library("tidyverse")
```

## Format Metadata

The most current 16S metadata is found in the Excel file METADATAFINAL_16S.xlsx

```{r format-combined-metadata, echo=FALSE}
rawMap <- read_xlsx("../documents/original_documents/16S/METADATAFINAL_16S.xlsx") # 77 x 26

#----- Remove Blank Columns & Extra Rows -----#
rawMapNoBlanks <- rawMap %>% 
  filter(!is.na(Neutropenic)) # 76 x 26 (1 row removed ("blank"))

#----- Format Column Names -----#
mapNewCols <- rawMapNoBlanks %>% 
  janitor::clean_names() %>% 
  rename(sample_name = aample_name)

#----- Change Factor Levels for Important Variables -----#

# important variables are:
#   "neutropenic"
#   "pre_post"
table(mapNewCols$neutropenic) # 56 Control, 20 Neutropenic
table(mapNewCols$pre_post) # 38 post, 38 pre

mapFinal <- mapNewCols %>% 
  mutate(across(c(neutropenic, pre_post), as.factor))

mapFinal$pre_post <- factor(mapFinal$pre_post, levels = c("PRE", "POST"))

mapFinal %>% 
  tabyl(neutropenic, pre_post)
```

```{r save-mapfinal, eval=FALSE}
saveRDS(mapFinal, "../data/RDataObjects/16S/metadataFinal.RDS")
```

